on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
name: CI
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-21.08
      options: --privileged
    steps:
    - uses: actions/checkout@v2
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      with:
        bundle: rsdkv5.flatpak
        manifest-path: com.decomp.RSDKv5.yaml
        cache-key: flatpak-builder-${{ github.sha }}
